services:
  - type: web
    name: mpc-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MEGAAPI_INSTANCE_ID
        sync: false
      - key: MEGAAPI_TOKEN
        sync: false
      - key: MEGAAPI_HOST
        value: apibusiness1.megaapi.com.br
      - key: GPT_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: MAKE_WEBHOOK_URL
        sync: false
    healthCheckPath: /api/v1/health
    autoDeploy: true