services:
  - type: web
    name: llm-router-api
    env: python
    buildCommand: |
      # Usar pip com flags para ignorar dependências
      export PIP_NO_DEPENDENCIES=1
      pip install --upgrade pip
      
      # Instalar pacotes individualmente com versões específicas
      pip install httpx==0.25.2 --no-deps
      pip install mistralai==0.0.12 --no-deps
      pip install httpcore==1.0.2 --no-deps
      pip install supabase==1.0.3 --no-deps
      pip install anthropic==0.18.1 --no-deps
      pip install openai==1.12.0 --no-deps
      
      # Dependências necessárias
      pip install pydantic==2.14.3 --no-deps
      pip install orjson==3.9.10 --no-deps
      pip install anyio==4.0.0 --no-deps
      pip install sniffio==1.3.0 --no-deps
      pip install certifi==2023.7.22 --no-deps
      pip install idna==3.4 --no-deps
      
      # Outros pacotes
      pip install fastapi==0.109.2 --no-deps
      pip install uvicorn==0.27.1 --no-deps
      pip install starlette==0.36.3 --no-deps
      pip install python-dotenv==1.0.1 --no-deps
      pip install requests==2.31.0 --no-deps
      pip install urllib3==2.0.5 --no-deps
      pip install charset-normalizer==3.3.2 --no-deps
      pip install tiktoken==0.5.2 --no-deps
      pip install regex==2023.8.8 --no-deps
      
      # Instalar opcionais
      pip install typing-extensions==4.7.1 --no-deps
      pip install h11==0.14.0 --no-deps
      pip install click==8.1.7 --no-deps
      pip install loguru==0.7.2 --no-deps
      pip install tenacity==8.2.3 --no-deps
      pip install rich==13.7.0 --no-deps
      
      # Pacotes extras para logging/auth
      pip install python-json-logger==2.0.7 --no-deps
      pip install python-jose==3.3.0 --no-deps
      pip install passlib==1.7.4 --no-deps
      pip install bcrypt==4.0.1 --no-deps
      
      # Dependências para Google Gemini
      pip install google-generativeai==0.3.2 --no-deps
      pip install google-api-core==2.15.0 --no-deps
      pip install googleapis-common-protos==1.62.0 --no-deps
      pip install protobuf==4.24.4 --no-deps
      pip install proto-plus==1.22.3 --no-deps
      
      # Neo4j e dependências relacionadas
      pip install neo4j==5.17.0 --no-deps
      pip install pytz==2023.3 --no-deps
      
      # Reinstalar só os mais críticos com dependências
      pip install --no-cache-dir --ignore-installed mistralai==0.0.12
      pip install --no-cache-dir --ignore-installed httpx==0.25.2
      
      # Imprimir instalados para debug
      pip list
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: MEGAAPI_INSTANCE_ID
        sync: false
      - key: MEGAAPI_API_KEY
        sync: false
      - key: MEGAAPI_TOKEN
        sync: false
    healthCheckPath: /api/v1/health
    autoDeploy: true