services:
  - type: web
    name: llm-router-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip cache purge
      
      # Criar diretório temporário para downloads
      mkdir -p /tmp/wheels
      
      # Baixar os wheels dos pacotes principais
      pip download httpx==0.25.2 -d /tmp/wheels
      pip download mistralai==0.0.12 -d /tmp/wheels
      pip download openai==1.12.0 -d /tmp/wheels
      pip download supabase==1.0.3 -d /tmp/wheels
      pip download anthropic==0.18.1 -d /tmp/wheels
      
      # Instalar apenas os wheels baixados, sem verificar dependências
      pip install --no-index --no-deps --find-links=/tmp/wheels httpx==0.25.2
      pip install --no-index --no-deps --find-links=/tmp/wheels mistralai==0.0.12
      pip install --no-index --no-deps --find-links=/tmp/wheels openai==1.12.0
      pip install --no-index --no-deps --find-links=/tmp/wheels supabase==1.0.3
      pip install --no-index --no-deps --find-links=/tmp/wheels anthropic==0.18.1
      
      # Instalar dependências comuns necessárias
      pip install pydantic==2.11.3
      pip install anyio==4.9.0
      pip install sniffio==1.3.1
      pip install typing-extensions==4.12.2
      pip install certifi==2024.12.14
      pip install orjson==3.10.15
      pip install httpcore==1.0.7
      
      # Instalar o resto dos pacotes exceto os que já instalamos
      pip install -r requirements.txt --no-deps
      
      # Instalar dependências finais
      pip install starlette==0.36.3
      pip install h11==0.14.0
      pip install click==8.1.8
      pip install idna==3.10
      pip install urllib3==2.3.0
      pip install charset-normalizer==3.4.1
      
      # Limpar arquivos temporários
      rm -rf /tmp/wheels
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: MEGAAPI_INSTANCE_ID
        sync: false
      - key: MEGAAPI_API_KEY
        sync: false
      - key: MEGAAPI_TOKEN
        sync: false
    healthCheckPath: /api/v1/health
    autoDeploy: true