services:
  - type: web
    name: llm-router-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip cache purge
      # Instalar mistralai primeiro para que suas dependências sejam respeitadas
      pip install mistralai==0.0.12
      # Depois instalar os outros pacotes não conflitantes
      pip install openai==1.12.0
      pip install supabase==1.0.3
      pip install anthropic==0.18.1
      # Por último, instalar o resto dos requerimentos
      pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: MEGAAPI_INSTANCE_ID
        sync: false
      - key: MEGAAPI_API_KEY
        sync: false
      - key: MEGAAPI_TOKEN
        sync: false
    healthCheckPath: /api/v1/health
    autoDeploy: true