services:
  # Web service
  - type: web
    name: llm-router-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && python run.py
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: API_HOST
        value: 0.0.0.0
      - key: PYTHON_VERSION
        value: 3.10.0