services:
  - type: web
    name: llm-router-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: MEGAAPI_INSTANCE_ID
        sync: false
      - key: MEGAAPI_API_KEY
        sync: false
      - key: MEGAAPI_TOKEN
        sync: false
    healthCheckPath: /api/v1/health
    autoDeploy: true