services:
  # Web service
  - type: web
    name: mpc-api
    env: python
    buildCommand: chmod +x api/scripts/preinstall.sh && ./api/scripts/preinstall.sh && pip install -r requirements.txt
    startCommand: cd api && python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MISTRAL_API_KEY
        sync: false
      - key: SUPABASE_URL
        value: https://bbexaorzfigomhktcvvq.supabase.co
      - key: SUPABASE_KEY
        sync: false